name: todo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  amplify_api: ^2.9.0
  amplify_auth_cognito: ^2.9.0
  amplify_authenticator: ^2.4.1
  amplify_flutter: ^2.9.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_lints: ^6.0.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  hive_ce: ^2.18.0
  hive_ce_flutter: ^2.3.4
  hooks_riverpod: ^3.0.3
  logger: ^2.6.2
  riverpod_annotation: ^3.0.3
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.10.5
  build_verify: ^3.1.1
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.3
  hive_ce_generator: ^1.10.0
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
